FROM debian:testing

RUN apt-get update && apt-get install -y \
# Required by racket for readline support
    libedit2 \
# racket 8.7+dfsg1-1
    racket \
# chez 9.5.8+dfsg-1
    chezscheme \
# mit-scheme 12.1-3
    mit-scheme \
# chicken 5.3.0-1
    chicken-bin \
# guile 3.0.8-2
    guile-3.0 \
# ikarus 0.0.3+bzr.2010.01.26+bap.1-1
    ikarus \
# scheme48 1.9.2-2
    scheme48 \
# scm 5f3-4
    scm \
# scheme9 2018.12.05-2
    scheme9 \
# gambit-c 4.9.3-1.2+b1
    gambc \
# stalin 0.11-7
    stalin \
# tinyscheme 1.42.svn.2020.06.04-2
    tinyscheme
